### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by JovanToroman** [JovanToroman/kefirnadar#2]
- [x] dodati validacije za sva polja prilikom unosa (lični podaci, email, telefon
- [x] izabrati minimum jedan način kontakta i jedan način deljenja
- [ ] dodati stilove (Bootstrap 4)
- [ ] dodati asinhroni proces koji će svakog dana povlačiti delioce starije od 30 dana iz baze
- [x] dodati obaveštenje ako nema nijednog korisnika koji deli zrnca u izabranom regionu
- [x] premestiti čišćenje korisnika iz app db-ja prilikom navigacije na početnu stranu u :start ključ kontrolera
